name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create ssh tunnel
        run: |
          sudo sshpass -p '@JTKPolban2021' ssh -o StrictHostKeyChecking=no -L 80:192.168.34.210:80 -L 443:192.168.34.210:443 -L 22:192.168.34.210:22 joe@103.209.131.3 -p 8022 &
      - name: Check for connection
        run: |
          telnet container-registry.7f000001.nip.io 22
